"""Deterministic fixture-site response scenarios."""

from __future__ import annotations

import json
from dataclasses import dataclass


@dataclass(frozen=True)
class FixtureResponse:
    """HTTP response generated by a fixture scenario."""

    status_code: int
    content_type: str
    body: str


def products_page() -> FixtureResponse:
    body = """
<!doctype html>
<html>
  <head><title>Fixture Products</title></head>
  <body>
    <h1>Fixture Products</h1>
    <script>
      fetch('/api/products?page=1').then((response) => response.json());
    </script>
  </body>
</html>
""".strip()
    return FixtureResponse(status_code=200, content_type="text/html; charset=utf-8", body=body)


def products_api(page: str) -> FixtureResponse:
    items_by_page = {
        "1": [
            {"id": "p1", "name": "Keyboard", "price": 120},
            {"id": "p2", "name": "Mouse", "price": 40},
        ],
        "2": [{"id": "p3", "name": "Monitor", "price": 300}],
    }
    body = json.dumps({"items": items_by_page.get(page, [])})
    return FixtureResponse(status_code=200, content_type="application/json", body=body)


def cloudflare_like_challenge() -> FixtureResponse:
    body = """
<!doctype html>
<html>
  <head><title>Just a moment...</title></head>
  <body>
    <h1>Checking if the site connection is secure</h1>
    <form id="challenge-form" action="/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page"></form>
  </body>
</html>
""".strip()
    return FixtureResponse(status_code=403, content_type="text/html; charset=utf-8", body=body)


def not_found() -> FixtureResponse:
    return FixtureResponse(
        status_code=404,
        content_type="text/plain; charset=utf-8",
        body="not found",
    )
